export const TODO_ACTIONS = {
    CREATE: 'CREATE',
    TOGGLE: 'TOGGLE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE'
}

export const VISIBILITY_FILTER_TYPES = {
    ALL: 'all',
    OPEN: 'open',
    DONE: 'done'
}

export const VISIBILITY_FILTER_ACTIONS = {
    SET: 'SET'
}

export const AUTHENTICATED_USER_ACTIONS = {
	SET_USER_NAME: 'SET_USER_NAME'
}

export const REST_PARAMETERS_ACTIONS = {
	SET_REST_PARAMETER_ATTRIBUTES_ACTIONS: 'SET_REST_PARAMETER_ATTRIBUTES_ACTIONS',
	SET_REST_PARAMETER_PAGE_SIZE_ACTIONS: 'SET_REST_PARAMETER_PAGE_SIZE_ACTIONS',
	SET_REST_PARAMETER_LINKS_ACTIONS: 'SET_REST_PARAMETER_LINKS_ACTIONS'
}
